#!/usr/bin/env php
<?php

define('MAKELOS_BASE_DIR', dirname(__FILE__));

if(!@include(dirname(__FILE__).DIRECTORY_SEPARATOR.'config'.DIRECTORY_SEPARATOR.'config.php')){
    defined('DS') || define('DS', DIRECTORY_SEPARATOR);
    defined('AK_FRAMEWORK_DIR')     || define('AK_FRAMEWORK_DIR',       AK_BASE_DIR.DS.'vendor'.DS.'akelos');
}

include AK_FRAMEWORK_DIR.DS.'makelos'.DS.'makelos.php';
