#!/usr/bin/env php
<?php

defined('DS') || define('DS', DIRECTORY_SEPARATOR);

if (isset($argv[1]) && strstr($argv[1], 'test:')){
    define('AK_ENVIRONMENT', 'testing');
}

if(is_file(dirname(__FILE__).DS.'config'.DS.'config.php')){
    include(dirname(__FILE__).DS.'config'.DS.'config.php');
}

if(defined('AK_FRAMEWORK_DIR')){
    include AK_FRAMEWORK_DIR.DS.'akelos_utils'.DS.'makelos'.DS.'makelos.php';
}elseif(!is_file('akelos_utils'.DS.'makelos'.DS.'makelos.php') || !include('akelos_utils'.DS.'makelos'.DS.'makelos.php')){
    include 'vendor'.DS.'akelos'.DS.'akelos_utils'.DS.'makelos'.DS.'makelos.php';
}