#!/usr/bin/env php
<?php

defined('DS') || define('DS', DIRECTORY_SEPARATOR);

if (isset($argv[1]) && strstr($argv[1], 'test:')){
    define('AK_ENVIRONMENT', 'testing');
}

if(is_file(dirname(realpath(__FILE__)).DS.'config'.DS.'config.php')){
    include(dirname(realpath(__FILE__)).DS.'config'.DS.'config.php');
}

if(defined('AK_FRAMEWORK_DIR')){
    include AK_FRAMEWORK_DIR.DS.'akelos_utils'.DS.'makelos'.DS.'makelos.php';
}elseif(!is_file(dirname(realpath(__FILE__)).DS.'akelos_utils'.DS.'makelos'.DS.'makelos.php') ||
        !include(dirname(realpath(__FILE__)).DS.'akelos_utils'.DS.'makelos'.DS.'makelos.php')) {

    if(is_file('vendor'.DS.'akelos'.DS.'akelos_utils'.DS.'makelos'.DS.'makelos.php')){
        include 'vendor'.DS.'akelos'.DS.'akelos_utils'.DS.'makelos'.DS.'makelos.php';
    }
}
