#!/usr/bin/env php
<?php

// Setup constants via the command line before loading the configuration
foreach($argv as $arg){
  if(preg_match('/^(AK_[^=]+)=([^ ]+)/', $arg, $matches)) define($matches[1], $matches[2]); 
}

define('AK_CONSOLE_MODE', true);
define('AK_ENABLE_AKELOS_ARGS', true);
defined('DS')           || define('DS', DIRECTORY_SEPARATOR);
defined('AK_BASE_DIR')  || define('AK_BASE_DIR', str_replace(DS.'script'.DS.'console','',__FILE__));

$_app_config_file = AK_BASE_DIR.DS.'config'.DS.'config.php';

if(file_exists($_app_config_file)){
    include(AK_BASE_DIR.DS.'config'.DS.'config.php');
}else{
    include(AK_BASE_DIR.DS.'test'.DS.'shared'.DS.'config'.DS.'config.php');
}
defined('AK_ENVIRONMENT')           || define('AK_ENVIRONMENT', 'testing');
require_once(AK_AKELOS_UTILS_DIR.DS.'scripts'.DS.'console.php');

