#!/usr/bin/env php
<?php

include(dirname(__FILE__).DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'config'.DIRECTORY_SEPARATOR.'config.php');
require_once(AK_ACTIVE_SUPPORT_DIR.DS.'utils'.DS.'scripts'.DS.'generate.php');

